# Generated by Django 5.1.4 on 2024-12-31 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ajy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО:')),
                ('bio', models.TextField(verbose_name='Биография:')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография:')),
            ],
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание:')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('date', models.DateTimeField(verbose_name='Дата:')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название:')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleOrNews',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('choices', models.CharField(choices=[('Article', 'Article'), ('News', 'News')], max_length=100, verbose_name='Место:')),
            ],
            bases=('main.basemodel',),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание:')),
                ('start_tour', models.DateTimeField(verbose_name='Дата начало:')),
                ('end_tour', models.DateField(verbose_name='Дата конец:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена (в долларах):')),
                ('ajy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_ajy', to='main.ajy', verbose_name='Ажы башчылар::')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_categories', to='main.categorypackage', verbose_name='Категория пакета:')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата урока:')),
                ('video_url', models.URLField(max_length=255, verbose_name='Ссылка на видео (YouTube):')),
                ('description', models.TextField(verbose_name='Описание урока:')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_packages', to='main.package', verbose_name='Пакеты')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка:')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_packages', to='main.package', verbose_name='Пакеты')),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('combo_choices', models.CharField(choices=[('FoodInfo', 'FoodInfo'), ('Requirements', 'Requirements'), ('Restrictions', 'Restrictions'), ('PlacesToVisit', 'PlacesToVisit'), ('YouGet', 'YouGet')], max_length=100, verbose_name='Место:')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='main.package', verbose_name='Пакеты')),
            ],
            bases=('main.basemodel',),
        ),
    ]
