# Generated by Django 5.1.4 on 2024-12-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajy',
            options={'verbose_name': 'Ажы', 'verbose_name_plural': 'Ажы'},
        ),
        migrations.AlterModelOptions(
            name='articleornews',
            options={'verbose_name': 'Статья или новость', 'verbose_name_plural': 'Статьи или новости'},
        ),
        migrations.AlterModelOptions(
            name='categorypackage',
            options={'verbose_name': 'Категория пакета', 'verbose_name_plural': 'Категории пакетов'},
        ),
        migrations.AlterModelOptions(
            name='combo',
            options={'verbose_name': 'Комбо', 'verbose_name_plural': 'Комбо'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Пакет', 'verbose_name_plural': 'Пакеты'},
        ),
        migrations.AlterModelOptions(
            name='photopackage',
            options={'verbose_name': 'Фото пакета', 'verbose_name_plural': 'Фото пакетов'},
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата:'),
        ),
    ]
