# Generated by Django 5.1.4 on 2025-01-23 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_basemodel_image_combophoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combophoto',
            name='combo',
        ),
        migrations.AddField(
            model_name='combophoto',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='combo_photos', to='main.package', verbose_name='Комбо'),
            preserve_default=False,
        ),
    ]
