# Generated by Django 5.1.4 on 2025-01-23 18:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_combophoto_combo_combophoto_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemodel',
            name='description',
        ),
        migrations.AddField(
            model_name='basemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка:'),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='rich',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='ComboPhoto',
        ),
    ]
