# Generated by Django 5.1.4 on 2025-02-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_basemodel_description_basemodel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
    ]
