# Generated by Django 5.1.4 on 2025-02-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='combo_choices',
            field=models.CharField(choices=[('FoodInfo', 'Информация о питании'), ('Requirements', 'Рекомендуется'), ('Restrictions', 'Не рекомендуется'), ('PlacesToVisit', 'Места для посещения'), ('YouGet', 'Что вы получите от нас')], max_length=100, verbose_name='Место:'),
        ),
    ]
