# Generated by Django 5.1.4 on 2025-02-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_combo_combo_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
