# Generated by Django 5.1.4 on 2025-01-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notification_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные уведомлений'),
        ),
    ]
