# Generated by Django 5.1.4 on 2025-01-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_client_notification_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='notification_data',
        ),
    ]
